os: linux
dist: xenial
language: csharp
solution: NEAReg.Lib.sln
mono: none
dotnet: 6.0
git:
  depth: false
install:
  - mkdir $HOME/dotnet_install && cd $HOME/dotnet_install
  - curl -L https://aka.ms/install-dotnet-preview -o install-dotnet-preview.sh
  - sudo bash install-dotnet-preview.sh
script:
 - dotnet restore
 - dotnet test NEARegLib.Tests -c Release